// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: STEventTraceCompressed.capnp

#ifndef CAPNP_INCLUDED_9274197a8c1bd9a8_
#define CAPNP_INCLUDED_9274197a8c1bd9a8_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 5003
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(e57f0f2c60992cf5);
CAPNP_DECLARE_SCHEMA(a549639de263753a);
CAPNP_DECLARE_SCHEMA(de81bb8c1098c164);
CAPNP_DECLARE_SCHEMA(87e1459470df7904);
CAPNP_DECLARE_SCHEMA(f39ea1239dd73c82);
enum class SyncType_f39ea1239dd73c82: uint16_t {
  SPAWN,
  JOIN,
  BARRIER,
  SYNC,
  LOCK,
  UNLOCK,
  COND_WAIT,
  COND_SIGNAL,
  COND_BROADCAST,
  SPIN_LOCK,
  SPIN_UNLOCK,
};
CAPNP_DECLARE_ENUM(SyncType, f39ea1239dd73c82);
CAPNP_DECLARE_SCHEMA(d2bf31fae8d0dc23);
CAPNP_DECLARE_SCHEMA(957495c263e2731b);
CAPNP_DECLARE_SCHEMA(8d9b0a9fce0b4a0b);
CAPNP_DECLARE_SCHEMA(86453f87c831d9e8);

}  // namespace schemas
}  // namespace capnp


struct EventStreamCompressed {
  EventStreamCompressed() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  struct Event;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(e57f0f2c60992cf5, 0, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct EventStreamCompressed::Event {
  Event() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    COMP,
    COMM,
    SYNC,
    MARKER,
  };
  struct AddrRange;
  struct CommEdge;
  typedef ::capnp::schemas::SyncType_f39ea1239dd73c82 SyncType;

  struct Comp;
  struct Comm;
  struct Sync;
  struct Marker;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(a549639de263753a, 3, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct EventStreamCompressed::Event::AddrRange {
  AddrRange() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(de81bb8c1098c164, 2, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct EventStreamCompressed::Event::CommEdge {
  CommEdge() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(87e1459470df7904, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct EventStreamCompressed::Event::Comp {
  Comp() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d2bf31fae8d0dc23, 3, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct EventStreamCompressed::Event::Comm {
  Comm() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(957495c263e2731b, 3, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct EventStreamCompressed::Event::Sync {
  Sync() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(8d9b0a9fce0b4a0b, 3, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

struct EventStreamCompressed::Event::Marker {
  Marker() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(86453f87c831d9e8, 3, 2)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand = &schema->defaultBrand;
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class EventStreamCompressed::Reader {
public:
  typedef EventStreamCompressed Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline bool hasEvents() const;
  inline  ::capnp::List< ::EventStreamCompressed::Event>::Reader getEvents() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class EventStreamCompressed::Builder {
public:
  typedef EventStreamCompressed Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasEvents();
  inline  ::capnp::List< ::EventStreamCompressed::Event>::Builder getEvents();
  inline void setEvents( ::capnp::List< ::EventStreamCompressed::Event>::Reader value);
  inline  ::capnp::List< ::EventStreamCompressed::Event>::Builder initEvents(unsigned int size);
  inline void adoptEvents(::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event>> disownEvents();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class EventStreamCompressed::Pipeline {
public:
  typedef EventStreamCompressed Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class EventStreamCompressed::Event::Reader {
public:
  typedef Event Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isComp() const;
  inline Comp::Reader getComp() const;

  inline bool isComm() const;
  inline Comm::Reader getComm() const;

  inline bool isSync() const;
  inline Sync::Reader getSync() const;

  inline bool isMarker() const;
  inline Marker::Reader getMarker() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class EventStreamCompressed::Event::Builder {
public:
  typedef Event Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isComp();
  inline Comp::Builder getComp();
  inline Comp::Builder initComp();

  inline bool isComm();
  inline Comm::Builder getComm();
  inline Comm::Builder initComm();

  inline bool isSync();
  inline Sync::Builder getSync();
  inline Sync::Builder initSync();

  inline bool isMarker();
  inline Marker::Builder getMarker();
  inline Marker::Builder initMarker();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class EventStreamCompressed::Event::Pipeline {
public:
  typedef Event Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class EventStreamCompressed::Event::AddrRange::Reader {
public:
  typedef AddrRange Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getStart() const;

  inline  ::uint64_t getEnd() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class EventStreamCompressed::Event::AddrRange::Builder {
public:
  typedef AddrRange Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getStart();
  inline void setStart( ::uint64_t value);

  inline  ::uint64_t getEnd();
  inline void setEnd( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class EventStreamCompressed::Event::AddrRange::Pipeline {
public:
  typedef AddrRange Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class EventStreamCompressed::Event::CommEdge::Reader {
public:
  typedef CommEdge Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline  ::uint16_t getProducerThread() const;

  inline  ::uint32_t getProducerEvent() const;

  inline bool hasAddrs() const;
  inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader getAddrs() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class EventStreamCompressed::Event::CommEdge::Builder {
public:
  typedef CommEdge Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint16_t getProducerThread();
  inline void setProducerThread( ::uint16_t value);

  inline  ::uint32_t getProducerEvent();
  inline void setProducerEvent( ::uint32_t value);

  inline bool hasAddrs();
  inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder getAddrs();
  inline void setAddrs( ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader value);
  inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder initAddrs(unsigned int size);
  inline void adoptAddrs(::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>> disownAddrs();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class EventStreamCompressed::Event::CommEdge::Pipeline {
public:
  typedef CommEdge Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class EventStreamCompressed::Event::Comp::Reader {
public:
  typedef Comp Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline  ::uint16_t getIops() const;

  inline  ::uint16_t getFlops() const;

  inline  ::uint16_t getWrites() const;

  inline  ::uint16_t getReads() const;

  inline bool hasWriteAddrs() const;
  inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader getWriteAddrs() const;

  inline bool hasReadAddrs() const;
  inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader getReadAddrs() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class EventStreamCompressed::Event::Comp::Builder {
public:
  typedef Comp Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint16_t getIops();
  inline void setIops( ::uint16_t value);

  inline  ::uint16_t getFlops();
  inline void setFlops( ::uint16_t value);

  inline  ::uint16_t getWrites();
  inline void setWrites( ::uint16_t value);

  inline  ::uint16_t getReads();
  inline void setReads( ::uint16_t value);

  inline bool hasWriteAddrs();
  inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder getWriteAddrs();
  inline void setWriteAddrs( ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader value);
  inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder initWriteAddrs(unsigned int size);
  inline void adoptWriteAddrs(::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>> disownWriteAddrs();

  inline bool hasReadAddrs();
  inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder getReadAddrs();
  inline void setReadAddrs( ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader value);
  inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder initReadAddrs(unsigned int size);
  inline void adoptReadAddrs(::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>> disownReadAddrs();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class EventStreamCompressed::Event::Comp::Pipeline {
public:
  typedef Comp Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class EventStreamCompressed::Event::Comm::Reader {
public:
  typedef Comm Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline bool hasEdges() const;
  inline  ::capnp::List< ::EventStreamCompressed::Event::CommEdge>::Reader getEdges() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class EventStreamCompressed::Event::Comm::Builder {
public:
  typedef Comm Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool hasEdges();
  inline  ::capnp::List< ::EventStreamCompressed::Event::CommEdge>::Builder getEdges();
  inline void setEdges( ::capnp::List< ::EventStreamCompressed::Event::CommEdge>::Reader value);
  inline  ::capnp::List< ::EventStreamCompressed::Event::CommEdge>::Builder initEdges(unsigned int size);
  inline void adoptEdges(::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::CommEdge>>&& value);
  inline ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::CommEdge>> disownEdges();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class EventStreamCompressed::Event::Comm::Pipeline {
public:
  typedef Comm Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class EventStreamCompressed::Event::Sync::Reader {
public:
  typedef Sync Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline  ::EventStreamCompressed::Event::SyncType getType() const;

  inline  ::uint64_t getId() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class EventStreamCompressed::Event::Sync::Builder {
public:
  typedef Sync Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::EventStreamCompressed::Event::SyncType getType();
  inline void setType( ::EventStreamCompressed::Event::SyncType value);

  inline  ::uint64_t getId();
  inline void setId( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class EventStreamCompressed::Event::Sync::Pipeline {
public:
  typedef Sync Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class EventStreamCompressed::Event::Marker::Reader {
public:
  typedef Marker Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand);
  }
#endif  // !CAPNP_LITE

  inline  ::uint16_t getCount() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class EventStreamCompressed::Event::Marker::Builder {
public:
  typedef Marker Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint16_t getCount();
  inline void setCount( ::uint16_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class EventStreamCompressed::Event::Marker::Pipeline {
public:
  typedef Marker Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline bool EventStreamCompressed::Reader::hasEvents() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool EventStreamCompressed::Builder::hasEvents() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::EventStreamCompressed::Event>::Reader EventStreamCompressed::Reader::getEvents() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event>>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::capnp::List< ::EventStreamCompressed::Event>::Builder EventStreamCompressed::Builder::getEvents() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event>>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void EventStreamCompressed::Builder::setEvents( ::capnp::List< ::EventStreamCompressed::Event>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event>>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::EventStreamCompressed::Event>::Builder EventStreamCompressed::Builder::initEvents(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event>>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS), size);
}
inline void EventStreamCompressed::Builder::adoptEvents(
    ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event>>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event>> EventStreamCompressed::Builder::disownEvents() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event>>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline  ::EventStreamCompressed::Event::Which EventStreamCompressed::Event::Reader::which() const {
  return _reader.getDataField<Which>(4 * ::capnp::ELEMENTS);
}
inline  ::EventStreamCompressed::Event::Which EventStreamCompressed::Event::Builder::which() {
  return _builder.getDataField<Which>(4 * ::capnp::ELEMENTS);
}

inline bool EventStreamCompressed::Event::Reader::isComp() const {
  return which() == EventStreamCompressed::Event::COMP;
}
inline bool EventStreamCompressed::Event::Builder::isComp() {
  return which() == EventStreamCompressed::Event::COMP;
}
inline EventStreamCompressed::Event::Comp::Reader EventStreamCompressed::Event::Reader::getComp() const {
  KJ_IREQUIRE(which() == EventStreamCompressed::Event::COMP,
              "Must check which() before get()ing a union member.");
  return EventStreamCompressed::Event::Comp::Reader(_reader);
}
inline EventStreamCompressed::Event::Comp::Builder EventStreamCompressed::Event::Builder::getComp() {
  KJ_IREQUIRE(which() == EventStreamCompressed::Event::COMP,
              "Must check which() before get()ing a union member.");
  return EventStreamCompressed::Event::Comp::Builder(_builder);
}
inline EventStreamCompressed::Event::Comp::Builder EventStreamCompressed::Event::Builder::initComp() {
  _builder.setDataField<EventStreamCompressed::Event::Which>(
      4 * ::capnp::ELEMENTS, EventStreamCompressed::Event::COMP);
  _builder.setDataField< ::uint16_t>(0 * ::capnp::ELEMENTS, 0);
  _builder.setDataField< ::uint16_t>(1 * ::capnp::ELEMENTS, 0);
  _builder.setDataField< ::uint16_t>(2 * ::capnp::ELEMENTS, 0);
  _builder.setDataField< ::uint16_t>(3 * ::capnp::ELEMENTS, 0);
  _builder.getPointerField(0 * ::capnp::POINTERS).clear();
  _builder.getPointerField(1 * ::capnp::POINTERS).clear();
  return EventStreamCompressed::Event::Comp::Builder(_builder);
}
inline bool EventStreamCompressed::Event::Reader::isComm() const {
  return which() == EventStreamCompressed::Event::COMM;
}
inline bool EventStreamCompressed::Event::Builder::isComm() {
  return which() == EventStreamCompressed::Event::COMM;
}
inline EventStreamCompressed::Event::Comm::Reader EventStreamCompressed::Event::Reader::getComm() const {
  KJ_IREQUIRE(which() == EventStreamCompressed::Event::COMM,
              "Must check which() before get()ing a union member.");
  return EventStreamCompressed::Event::Comm::Reader(_reader);
}
inline EventStreamCompressed::Event::Comm::Builder EventStreamCompressed::Event::Builder::getComm() {
  KJ_IREQUIRE(which() == EventStreamCompressed::Event::COMM,
              "Must check which() before get()ing a union member.");
  return EventStreamCompressed::Event::Comm::Builder(_builder);
}
inline EventStreamCompressed::Event::Comm::Builder EventStreamCompressed::Event::Builder::initComm() {
  _builder.setDataField<EventStreamCompressed::Event::Which>(
      4 * ::capnp::ELEMENTS, EventStreamCompressed::Event::COMM);
  _builder.getPointerField(0 * ::capnp::POINTERS).clear();
  return EventStreamCompressed::Event::Comm::Builder(_builder);
}
inline bool EventStreamCompressed::Event::Reader::isSync() const {
  return which() == EventStreamCompressed::Event::SYNC;
}
inline bool EventStreamCompressed::Event::Builder::isSync() {
  return which() == EventStreamCompressed::Event::SYNC;
}
inline EventStreamCompressed::Event::Sync::Reader EventStreamCompressed::Event::Reader::getSync() const {
  KJ_IREQUIRE(which() == EventStreamCompressed::Event::SYNC,
              "Must check which() before get()ing a union member.");
  return EventStreamCompressed::Event::Sync::Reader(_reader);
}
inline EventStreamCompressed::Event::Sync::Builder EventStreamCompressed::Event::Builder::getSync() {
  KJ_IREQUIRE(which() == EventStreamCompressed::Event::SYNC,
              "Must check which() before get()ing a union member.");
  return EventStreamCompressed::Event::Sync::Builder(_builder);
}
inline EventStreamCompressed::Event::Sync::Builder EventStreamCompressed::Event::Builder::initSync() {
  _builder.setDataField<EventStreamCompressed::Event::Which>(
      4 * ::capnp::ELEMENTS, EventStreamCompressed::Event::SYNC);
  _builder.setDataField< ::uint16_t>(0 * ::capnp::ELEMENTS, 0);
  _builder.setDataField< ::uint64_t>(2 * ::capnp::ELEMENTS, 0);
  return EventStreamCompressed::Event::Sync::Builder(_builder);
}
inline bool EventStreamCompressed::Event::Reader::isMarker() const {
  return which() == EventStreamCompressed::Event::MARKER;
}
inline bool EventStreamCompressed::Event::Builder::isMarker() {
  return which() == EventStreamCompressed::Event::MARKER;
}
inline EventStreamCompressed::Event::Marker::Reader EventStreamCompressed::Event::Reader::getMarker() const {
  KJ_IREQUIRE(which() == EventStreamCompressed::Event::MARKER,
              "Must check which() before get()ing a union member.");
  return EventStreamCompressed::Event::Marker::Reader(_reader);
}
inline EventStreamCompressed::Event::Marker::Builder EventStreamCompressed::Event::Builder::getMarker() {
  KJ_IREQUIRE(which() == EventStreamCompressed::Event::MARKER,
              "Must check which() before get()ing a union member.");
  return EventStreamCompressed::Event::Marker::Builder(_builder);
}
inline EventStreamCompressed::Event::Marker::Builder EventStreamCompressed::Event::Builder::initMarker() {
  _builder.setDataField<EventStreamCompressed::Event::Which>(
      4 * ::capnp::ELEMENTS, EventStreamCompressed::Event::MARKER);
  _builder.setDataField< ::uint16_t>(0 * ::capnp::ELEMENTS, 0);
  return EventStreamCompressed::Event::Marker::Builder(_builder);
}
inline  ::uint64_t EventStreamCompressed::Event::AddrRange::Reader::getStart() const {
  return _reader.getDataField< ::uint64_t>(
      0 * ::capnp::ELEMENTS);
}

inline  ::uint64_t EventStreamCompressed::Event::AddrRange::Builder::getStart() {
  return _builder.getDataField< ::uint64_t>(
      0 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::AddrRange::Builder::setStart( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      0 * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t EventStreamCompressed::Event::AddrRange::Reader::getEnd() const {
  return _reader.getDataField< ::uint64_t>(
      1 * ::capnp::ELEMENTS);
}

inline  ::uint64_t EventStreamCompressed::Event::AddrRange::Builder::getEnd() {
  return _builder.getDataField< ::uint64_t>(
      1 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::AddrRange::Builder::setEnd( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      1 * ::capnp::ELEMENTS, value);
}

inline  ::uint16_t EventStreamCompressed::Event::CommEdge::Reader::getProducerThread() const {
  return _reader.getDataField< ::uint16_t>(
      0 * ::capnp::ELEMENTS);
}

inline  ::uint16_t EventStreamCompressed::Event::CommEdge::Builder::getProducerThread() {
  return _builder.getDataField< ::uint16_t>(
      0 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::CommEdge::Builder::setProducerThread( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      0 * ::capnp::ELEMENTS, value);
}

inline  ::uint32_t EventStreamCompressed::Event::CommEdge::Reader::getProducerEvent() const {
  return _reader.getDataField< ::uint32_t>(
      1 * ::capnp::ELEMENTS);
}

inline  ::uint32_t EventStreamCompressed::Event::CommEdge::Builder::getProducerEvent() {
  return _builder.getDataField< ::uint32_t>(
      1 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::CommEdge::Builder::setProducerEvent( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      1 * ::capnp::ELEMENTS, value);
}

inline bool EventStreamCompressed::Event::CommEdge::Reader::hasAddrs() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool EventStreamCompressed::Event::CommEdge::Builder::hasAddrs() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader EventStreamCompressed::Event::CommEdge::Reader::getAddrs() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder EventStreamCompressed::Event::CommEdge::Builder::getAddrs() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void EventStreamCompressed::Event::CommEdge::Builder::setAddrs( ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder EventStreamCompressed::Event::CommEdge::Builder::initAddrs(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS), size);
}
inline void EventStreamCompressed::Event::CommEdge::Builder::adoptAddrs(
    ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>> EventStreamCompressed::Event::CommEdge::Builder::disownAddrs() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline  ::uint16_t EventStreamCompressed::Event::Comp::Reader::getIops() const {
  return _reader.getDataField< ::uint16_t>(
      0 * ::capnp::ELEMENTS);
}

inline  ::uint16_t EventStreamCompressed::Event::Comp::Builder::getIops() {
  return _builder.getDataField< ::uint16_t>(
      0 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::Comp::Builder::setIops( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      0 * ::capnp::ELEMENTS, value);
}

inline  ::uint16_t EventStreamCompressed::Event::Comp::Reader::getFlops() const {
  return _reader.getDataField< ::uint16_t>(
      1 * ::capnp::ELEMENTS);
}

inline  ::uint16_t EventStreamCompressed::Event::Comp::Builder::getFlops() {
  return _builder.getDataField< ::uint16_t>(
      1 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::Comp::Builder::setFlops( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      1 * ::capnp::ELEMENTS, value);
}

inline  ::uint16_t EventStreamCompressed::Event::Comp::Reader::getWrites() const {
  return _reader.getDataField< ::uint16_t>(
      2 * ::capnp::ELEMENTS);
}

inline  ::uint16_t EventStreamCompressed::Event::Comp::Builder::getWrites() {
  return _builder.getDataField< ::uint16_t>(
      2 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::Comp::Builder::setWrites( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      2 * ::capnp::ELEMENTS, value);
}

inline  ::uint16_t EventStreamCompressed::Event::Comp::Reader::getReads() const {
  return _reader.getDataField< ::uint16_t>(
      3 * ::capnp::ELEMENTS);
}

inline  ::uint16_t EventStreamCompressed::Event::Comp::Builder::getReads() {
  return _builder.getDataField< ::uint16_t>(
      3 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::Comp::Builder::setReads( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      3 * ::capnp::ELEMENTS, value);
}

inline bool EventStreamCompressed::Event::Comp::Reader::hasWriteAddrs() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool EventStreamCompressed::Event::Comp::Builder::hasWriteAddrs() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader EventStreamCompressed::Event::Comp::Reader::getWriteAddrs() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder EventStreamCompressed::Event::Comp::Builder::getWriteAddrs() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void EventStreamCompressed::Event::Comp::Builder::setWriteAddrs( ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder EventStreamCompressed::Event::Comp::Builder::initWriteAddrs(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS), size);
}
inline void EventStreamCompressed::Event::Comp::Builder::adoptWriteAddrs(
    ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>> EventStreamCompressed::Event::Comp::Builder::disownWriteAddrs() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline bool EventStreamCompressed::Event::Comp::Reader::hasReadAddrs() const {
  return !_reader.getPointerField(1 * ::capnp::POINTERS).isNull();
}
inline bool EventStreamCompressed::Event::Comp::Builder::hasReadAddrs() {
  return !_builder.getPointerField(1 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader EventStreamCompressed::Event::Comp::Reader::getReadAddrs() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::get(
      _reader.getPointerField(1 * ::capnp::POINTERS));
}
inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder EventStreamCompressed::Event::Comp::Builder::getReadAddrs() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::get(
      _builder.getPointerField(1 * ::capnp::POINTERS));
}
inline void EventStreamCompressed::Event::Comp::Builder::setReadAddrs( ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::set(
      _builder.getPointerField(1 * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::EventStreamCompressed::Event::AddrRange>::Builder EventStreamCompressed::Event::Comp::Builder::initReadAddrs(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::init(
      _builder.getPointerField(1 * ::capnp::POINTERS), size);
}
inline void EventStreamCompressed::Event::Comp::Builder::adoptReadAddrs(
    ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::adopt(
      _builder.getPointerField(1 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>> EventStreamCompressed::Event::Comp::Builder::disownReadAddrs() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::AddrRange>>::disown(
      _builder.getPointerField(1 * ::capnp::POINTERS));
}

inline bool EventStreamCompressed::Event::Comm::Reader::hasEdges() const {
  return !_reader.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline bool EventStreamCompressed::Event::Comm::Builder::hasEdges() {
  return !_builder.getPointerField(0 * ::capnp::POINTERS).isNull();
}
inline  ::capnp::List< ::EventStreamCompressed::Event::CommEdge>::Reader EventStreamCompressed::Event::Comm::Reader::getEdges() const {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::CommEdge>>::get(
      _reader.getPointerField(0 * ::capnp::POINTERS));
}
inline  ::capnp::List< ::EventStreamCompressed::Event::CommEdge>::Builder EventStreamCompressed::Event::Comm::Builder::getEdges() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::CommEdge>>::get(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}
inline void EventStreamCompressed::Event::Comm::Builder::setEdges( ::capnp::List< ::EventStreamCompressed::Event::CommEdge>::Reader value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::CommEdge>>::set(
      _builder.getPointerField(0 * ::capnp::POINTERS), value);
}
inline  ::capnp::List< ::EventStreamCompressed::Event::CommEdge>::Builder EventStreamCompressed::Event::Comm::Builder::initEdges(unsigned int size) {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::CommEdge>>::init(
      _builder.getPointerField(0 * ::capnp::POINTERS), size);
}
inline void EventStreamCompressed::Event::Comm::Builder::adoptEdges(
    ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::CommEdge>>&& value) {
  ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::CommEdge>>::adopt(
      _builder.getPointerField(0 * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::List< ::EventStreamCompressed::Event::CommEdge>> EventStreamCompressed::Event::Comm::Builder::disownEdges() {
  return ::capnp::_::PointerHelpers< ::capnp::List< ::EventStreamCompressed::Event::CommEdge>>::disown(
      _builder.getPointerField(0 * ::capnp::POINTERS));
}

inline  ::EventStreamCompressed::Event::SyncType EventStreamCompressed::Event::Sync::Reader::getType() const {
  return _reader.getDataField< ::EventStreamCompressed::Event::SyncType>(
      0 * ::capnp::ELEMENTS);
}

inline  ::EventStreamCompressed::Event::SyncType EventStreamCompressed::Event::Sync::Builder::getType() {
  return _builder.getDataField< ::EventStreamCompressed::Event::SyncType>(
      0 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::Sync::Builder::setType( ::EventStreamCompressed::Event::SyncType value) {
  _builder.setDataField< ::EventStreamCompressed::Event::SyncType>(
      0 * ::capnp::ELEMENTS, value);
}

inline  ::uint64_t EventStreamCompressed::Event::Sync::Reader::getId() const {
  return _reader.getDataField< ::uint64_t>(
      2 * ::capnp::ELEMENTS);
}

inline  ::uint64_t EventStreamCompressed::Event::Sync::Builder::getId() {
  return _builder.getDataField< ::uint64_t>(
      2 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::Sync::Builder::setId( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      2 * ::capnp::ELEMENTS, value);
}

inline  ::uint16_t EventStreamCompressed::Event::Marker::Reader::getCount() const {
  return _reader.getDataField< ::uint16_t>(
      0 * ::capnp::ELEMENTS);
}

inline  ::uint16_t EventStreamCompressed::Event::Marker::Builder::getCount() {
  return _builder.getDataField< ::uint16_t>(
      0 * ::capnp::ELEMENTS);
}
inline void EventStreamCompressed::Event::Marker::Builder::setCount( ::uint16_t value) {
  _builder.setDataField< ::uint16_t>(
      0 * ::capnp::ELEMENTS, value);
}


#endif  // CAPNP_INCLUDED_9274197a8c1bd9a8_
